markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: accbest
author: "刘威"
email: lwmain#163.com
name: "刘威个人博客"
url: http://www.accnew.com
domain: www.accnew.com
all_categories: [
["env", "环境科技","/posts/env.html"], 
["program", "软件编程","/posts/program.html"],
["quant", "量化金融","/posts/quant.html"], 
["linux", "Linux C","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
